################## 系统配置 ##################

search:
  includes:
    - post
    - page

################## 样式配置 ##################

# 图片配置
image:
  favicon: "https://ga.candinya.com/avatar/a7f9e15fef26e0a540edc977e21cb3eb" # 站点图标
  avatar: "https://ga.candinya.com/avatar/a7f9e15fef26e0a540edc977e21cb3eb" # 个人信息挂件上的头像
  banner:
    light: "/assets/banner.webp"
    dark: "/assets/banner_dark.webp"
  background:
    light: "/assets/bg.webp"
    dark: "/assets/bg_dark.webp"

# 顶部导航栏配置
nav:
  items:
    - label: 首页
      icon: home
      url: /
    - label: 档案馆
      icon: file
      url: /archives/
    - label: 好伙伴
      icon: paw
      url: /friends/
    - label: 链接
      icon: link
      submenu:
        - label: 作者博客
          icon: star
          url: https://candinya.com
        - label: 项目链接
          icon: code
          url: https://github.com/Candinya/Kratos-Rebirth

# Footer 页脚配置
footer:
  links:
    - icon: users
      link: https://matrix.to/#/#CandyUnion:nya.one
    - icon: github
      link: https://github.com/Candinya
    - html: <svg fill="currentColor" viewBox="0 0 1024 1024"><path d="M512,0C794.58,0 1024,229.42 1024,512C1024,794.58 794.58,1024 512,1024C229.42,1024 0,794.58 0,512C0,229.42 229.42,0 512,0ZM292.789,304.042L292.789,723.567C292.789,750.225 314.432,771.868 341.091,771.868C367.749,771.868 389.393,750.225 389.393,723.567L389.393,440.596L641.699,748.461C650.156,762.483 665.536,771.868 683.091,771.868C709.749,771.868 731.393,750.225 731.393,723.567L731.393,304.042C731.393,277.384 709.749,255.74 683.091,255.74C664.98,255.74 649.184,265.729 640.916,280.494L565.431,372.601L565.452,372.618C558.836,380.884 554.877,391.367 554.877,402.768C554.877,429.426 576.521,451.07 603.179,451.07C615.262,451.07 626.315,446.624 634.789,439.28L634.789,587.625L383.634,281.165C375.473,266.033 359.474,255.74 341.091,255.74C314.432,255.74 292.789,277.384 292.789,304.042Z" /></svg>
      link: https://nya.one/@Candinya
      addition: rel="me" target="_blank"
    - icon: rss
      link: /atom.xml
  components:
    uptime:
      since: "2018/05/06 17:03:12"
      text: "本站已在风雨中飘摇"
    author:
      homepage: "https://ncd.moe"
    additional: # 托管信息等
      - - 由 <a href="https://hexo.io" target="_blank" rel="nofollow">Hexo</a> 强力驱动
        - 在 <a href="https://github.io" target="_blank">Github Pages</a> 暖心托管

# 代码高亮
# syntax_highlighter:
#   theme: atom-dark # 代码高亮主题（请参照具体的高亮插件对应的主题样式）

# Widgets 侧边栏小挂件
sidebar:
  widgets:
    - about
    - splitter
    - toc
    - category
    - tagcloud
    - posts

# 分享组件设置
share:
  enable: true
  title: "分享这一刻"
  message: "让朋友们也来瞅瞅！"
  platforms:
    - name: "QQ"
      icon: "qq"
      color: "#00bfff"
      link: "https://connect.qq.com/widget/shareqq/index.html?url=$URL&title=$TITLE&desc=&summary=$SUMMARY&site=$SITE"
    - name: "QQ空间"
      icon: "star"
      color: "#fece00"
      link: "https://sns.qzone.qq.com/cgi-bin/qzshare/cgi_qzshare_onekey?url=$URL&title=$TITLE&desc=&summary=$SUMMARY&site=$SITE"
    - name: "微博"
      icon: "weibo"
      color: "#e6162d"
      link: "https://service.weibo.com/share/share.php?url=$URL&title=$TITLE"
    - name: "X"
      html: |
        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="icon icon-tabler icons-tabler-outline icon-tabler-brand-x">
          <path stroke="none" d="M0 0h24v24H0z" fill="none" />
          <path d="M4 4l11.733 16h4.267l-11.733 -16z" />
          <path d="M4 20l6.768 -6.768m2.46 -2.46l6.772 -6.772" />
        </svg>
      color: "#000"
      link: "https://x.com/intent/tweet?text=$TITLE&url=$URL"
    - name: "Facebook"
      icon: "facebook"
      color: "#3e569b"
      link: "https://www.facebook.com/sharer/sharer.php?u=$URL"
    - name: "喵窝"
      html: <svg fill="currentColor" width="18" height="18" viewBox="0 0 329 388"><path d="M0,36.226c0,-19.993 16.233,-36.226 36.226,-36.226c13.788,0 25.787,7.719 31.908,19.068l188.366,229.845l0,-111.259c-6.356,5.508 -14.645,8.843 -23.707,8.843c-19.994,0 -36.226,-16.232 -36.226,-36.226c-0,-8.551 2.968,-16.413 7.93,-22.613l-0.015,-0.013l56.614,-69.08c6.2,-11.073 18.047,-18.565 31.63,-18.565c19.994,0 36.227,16.233 36.227,36.226l-0,314.644c-0,19.994 -16.233,36.226 -36.227,36.226c-13.166,0 -24.701,-7.039 -31.044,-17.555l-189.229,-230.899l-0,212.228c-0,19.994 -16.233,36.226 -36.227,36.226c-19.993,0 -36.226,-16.232 -36.226,-36.226l0,-314.644Z" /></svg>
      color: "#62b6e7"
      link: "https://nya.one/share?text=%3E%20$TITLE%0A%3E%0A%3E%20$SUMMARY%0A----%20$SITE%0A%0A$URL"

# 打赏组件设置
donate:
  enable: true
  title: "赞助喵"
  message: 非常感谢您的喜欢！ <i class="fa fa-heart" style="color:#d43f57"></i>
  qrcode_placeholder: "/assets/donate.png"
  platforms:
    - name: "Ethereum"
      html: |
        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="icon icon-tabler icons-tabler-outline icon-tabler-currency-ethereum">
          <path stroke="none" d="M0 0h24v24H0z" fill="none" />
          <path d="M6 12l6 -9l6 9l-6 9z" />
          <path d="M6 12l6 -3l6 3l-6 2z" />
        </svg>
      color: "#8a92b2"
      qrcode: "0xexample_address"
    - name: "BitCoin"
      icon: "bitcoin"
      color: "#ee7c2f"
      qrcode: "example_address"
    - name: "支付宝"
      html: |
        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="icon icon-tabler icons-tabler-outline icon-tabler-brand-alipay">
          <path stroke="none" d="M0 0h24v24H0z" fill="none" />
          <path d="M19 3h-14a2 2 0 0 0 -2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2 -2v-14a2 2 0 0 0 -2 -2z" />
          <path d="M7 7h10" />
          <path d="M12 3v7" />
          <path d="M21 17.314c-2.971 -1.923 -15 -8.779 -15 -1.864c0 1.716 1.52 2.55 2.985 2.55c3.512 0 6.814 -5.425 6.814 -8h-6.604" />
        </svg>
      color: "#1677ff"
      qrcode: "example_alipay"
    - name: "微信支付"
      icon: "wechat"
      color: "#38ad5a"
      qrcode: "example_wechatpay"
    - name: "Credit Card"
      icon: "credit-card"
      color: "green"
      link: "https://candinya.com"

# 版权说明
copyright_notice:
  in_page:
    enable_at:
      - post
      - page

# 评论系统
comments:
  core:
    enable_at:
      # - index
      - post
      - page
    template:
      _shared: |
        <script>
          (() => {
            const loadComments = async () => {
              if (typeof Gitalk === "undefined") {
                // 还未就绪，等一会再试试吧
                setTimeout(loadComments, 100);
              } else {
                // 准备好了，开始加载
                const path = "$PATH";
                // const hashID = await window.crypto.subtle.digest("SHA-1", new TextEncoder().encode(path));
                const hashID = path;
                const gitalk = new Gitalk(Object.assign({
                    id: hashID,
                    path: path,
                }, {
                  clientID: 'GitHub Application Client ID',
                  clientSecret: 'GitHub Application Client Secret',
                  repo: "demo-comments",
                  owner: "kratos-rebirth",
                  admin: ["Candinya"],
                  distractionFreeMode: false,
                }));

                gitalk.render('gitalk-container');
              }
            };

            window.loadComments = loadComments;
          })();
        </script>
      index: ""
      post: <div id="gitalk-container" class="kr-comments lazy-load"></div>
      page: <div id="gitalk-container" class="kr-comments lazy-load"></div>
  count:
    enable_at:
      []
      # - index
      # - post
    template:
      _shared: ""
      index: ""
      post: ""

# 访问数量统计
visit_count:
  enable_at:
    []
    # - index
    # - post
  template:
    _shared: ""
    index: ""
    post: ""

################## 额外的注入代码 ##################
additional_injections:
  head: | # 搜索引擎验证，或是追加的样式表
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/gitalk/1.8.0/gitalk.min.css" integrity="sha512-0hsIlRjJbiUWaKMhXXNDmjWI2qPvUlhNBLHMhqeF5jIma+bedec27N5FoT2JEeHz5TUmOGCsm1Y89EsX/P0wOg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <style>
      .gt-counts,
      .gt-header-textarea,
      .gt-user-name {
        color: var(--kr-theme-text) !important;
      }

      .gt-header-textarea,
      .gt-header-preview,
      .gt-btn-preview,
      .gt-comment-content,
      .gt-popup {
        background-color: var(--kr-theme-page-bg) !important;
      }

      .gt-popup {
        border-color: #6190e8 !important;
      }

      .gt-header-textarea {
        background: url("/assets/comment.webp") right bottom no-repeat;
      }
    </style>
  footer: ""
  after_footer: | # 站点分析，或是追加的脚本
    <script src="https://cdnjs.cloudflare.com/ajax/libs/gitalk/1.8.0/gitalk.min.js" integrity="sha512-Z6q/CxNjbGeWbPamDjp/I737f5LnynAOjJl85FlT75YW3eWmldnn2wj3nhMVEaqMeatyUmvKyfCaM5TND0yRhQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
